name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6
  gradient_borders: ^1.0.0
  morphable_shape: ^1.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter


flutter_gen:
  output: lib/

flutter:
  uses-material-design: true
  assets:
    - assets/DiversityAvatars/
    - assets/logo/
    - assets/bg/
    - assets/icons/
